# Generated by Django 4.1 on 2022-09-08 04:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('account_name', models.CharField(max_length=15)),
                ('balance', models.IntegerField()),
                ('pin', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=7)),
                ('address', models.TextField()),
                ('age', models.PositiveSmallIntegerField()),
                ('nationality', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('signature', models.ImageField(default='default.jpg', upload_to='headshot')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(max_length=10)),
                ('receipt_date', models.DateTimeField(default=datetime.datetime.now)),
                ('bill_number', models.IntegerField()),
                ('total_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('amount', models.BigIntegerField()),
                ('account_pin', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.account')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.IntegerField()),
                ('transaction_number', models.IntegerField()),
                ('transaction_type', models.CharField(max_length=15)),
                ('transaction_charge', models.IntegerField()),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_destination', to='wallet.account')),
                ('origin_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transaction_original_account', to='wallet.account')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdPary',
            fields=[
                ('nameof_thirdparty', models.CharField(max_length=13)),
                ('transaction_account', models.IntegerField()),
                ('location', models.CharField(max_length=15)),
                ('currency', models.CharField(max_length=12)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.account')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('customer_id', models.IntegerField()),
                ('gender_1', models.CharField(max_length=11)),
                ('zpoints', models.IntegerField()),
                ('date_of_reward', models.DateTimeField(default=datetime.datetime.now)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=100)),
                ('title', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(max_length=11)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('loan_type', models.CharField(max_length=20)),
                ('amount', models.BigIntegerField()),
                ('loan_balance', models.IntegerField()),
                ('interst_rate', models.IntegerField()),
                ('payment_duedate', models.DateTimeField(default=datetime.datetime.now)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField()),
                ('card_pin', models.IntegerField()),
                ('debit_card', models.CharField(max_length=10)),
                ('credit_card', models.CharField(max_length=12)),
                ('date_issued', models.DateTimeField(default=datetime.datetime.now)),
                ('issuer', models.CharField(max_length=7)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_b', to='wallet.account')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
        ),
    ]
