# Generated by Django 4.1 on 2022-08-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='signature',
            field=models.ImageField(default='default.jpg', upload_to='headshot'),
        ),
    ]
